version: "3.8"

services:
  auth_service_db:
      image: postgres:latest
      container_name: auth_service_db
      environment:
        - POSTGRES_DB=auth_service_db
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
      ports:
        - "5432:5432"
      volumes:
        - db_data:/var/lib/postgresql/data
      networks:
        - app-network
        
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - "5000:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth_service_db:5432/auth_service_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - auth_service_db
    networks:
      - app-network

  course-service:
    build:
      context: ../services/course-service
      dockerfile: Dockerfile
    image: course-service:latest
    ports:
      - "5001:8080"

  video-service:
    build:
      context: ../services/video-service
      dockerfile: Dockerfile
    image: video-service:latest
    ports:
      - "5002:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: my-angular-app:latest
    ports:
      - "4200:80"
    networks:
      - app-network

  

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  db_test_data:
