name: CI Auth Service Workflow

on:
  push:
    branches:
      - '*'
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test Auth Service
        run: |
          cd services/auth-service
          mvn clean install
          mvn test

      - name: Package the Application
        run: |
          cd services/auth-service
          mvn package
